### ISSUE TITLE
Congratulate 🎉

### ISSUE THREAD

**Issue by 1995parham** [Tabrizian/msc-thesis#1]
Iman, it is great to graduate from U of T. I think you are one the smartest person I have ever seen, it is my honor to be your friend. also, it was great to be your colleague at @aolab. Canada must proud to have you. Continue your awesome works and be happy :muscle:

**Comment by Tabrizian** [comment]
@1995parham Thanks Parham Jan! I have always learnt from you so much!! There is not a single day that I don't look up something to see how you handled it ❤️ Hope our paths cross again!
